//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OA.Moel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfo()
        {
            this.RoleInfo = new HashSet<RoleInfo>();
        }
    
        public int id { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string DateOfBirth { get; set; }
        public string Address { get; set; }
        public string Nationality { get; set; }
        public string Email { get; set; }
        public string Occupation { get; set; }
        public string FullName { get; set; }
        public int DelFlag { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public System.DateTime JoinTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleInfo> RoleInfo { get; set; }
    }
}
